version: '2.1'
services:
  discovery-server:
    ports:
      - "8761:8761"
    build:
      logs-bugs-discovery-server
  programmer-email-provider:
    build:
      logs-bugs-email-provider
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - POSTGRES_PASSWORD=643aceb9dae35f7d22e4fd7b4ebdc02e7290a04808c903c8477ed988b1a3a985
     
  assigner-email-provider:
    build:
      logs-bugs-assigner-mail-provider 
    mem_limit: 350m
    mem_reservation: 100M 
  email-notifier:
    build:
      logs-bugs-email-notifier
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - MAIL_PASSWORD=nshkvbxqzylrwkoz
      - KAFKA_PASSWORD=5YGnUuvAvVF4_1XXZXdNT4KXA2bydtcm
  analyzer:
    build:
      logs-analyzer
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - KAFKA_PASSWORD=5YGnUuvAvVF4_1XXZXdNT4KXA2bydtcm
  bugs-openning:
    build:
      logs-bugs-openning
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - POSTGRES_PASSWORD=643aceb9dae35f7d22e4fd7b4ebdc02e7290a04808c903c8477ed988b1a3a985
      - KAFKA_PASSWORD=5YGnUuvAvVF4_1XXZXdNT4KXA2bydtcm
  reporter-back-office:
    ports:
      - "8282:8282"
    build:
      logs-bugs-reporter-back-office
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - POSTGRES_PASSWORD=643aceb9dae35f7d22e4fd7b4ebdc02e7290a04808c903c8477ed988b1a3a985
  db-populator:
    build:
       logs-db-populator
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - MONGO_PASSWORD=12345.com
      - KAFKA_PASSWORD=5YGnUuvAvVF4_1XXZXdNT4KXA2bydtcm
  info-back-office:
    ports:
      - "8383:8080"
    build:
       logs-info-back-office
    mem_limit: 350m
    mem_reservation: 100M
    environment:
      - MONGO_PASSWORD=12345.com


  
        
  
  