version: '2.1'
services:
  programmer-email-provider:
    ports:
      - "8284:8284"
    build:
      logs-bugs-email-provider
  assigner-email-provider:
    ports:
      - "8283:8283"
    build:
      logs-bugs-assigner-mail-provider  
  email-notifier:
    build:
      logs-bugs-email-notifier
  analyzer:
    build:
      logs-analyzer
  bugs-openning:
    build:
      logs-bugs-openning
  reporter-back-office:
    ports:
      - "8282:8282"
    build:
      logs-bugs-reporter-back-office
  db-populator:
    build:
       logs-db-populator
  info-back-office:
    build:
       logs-info-back-office
  
        
  
  